export const ProductType = {
    PRODUCTTYPE: "PRODUCT",
    CARTPRODUCTTYPE: "CARTPRODUCTTYPE",
    REMOVEPRODUCTTYPE: "REMOVEPRODUCTTYPE",     
    REMOVEALLPRODUCTTYPE: "REMOVEALLPRODUCTTYPE",
    INCREMENTPRODUCTTYPE: "INCREMENTPRODUCTTYPE",
    DECREMENTPRODUCTTYPE: "DECREMENTPRODUCTTYPE",
    WISHLISTPRODUCTTYPE: "WISHLISTPRODUCTTYPE",
    REMOVEWISHLISTPRODUCTTYPE: "REMOVEWISHLISTPRODUCTTYPE",
    REMOVEALLWISHLISTPRODUCTTYPE: "REMOVEALLWISHLISTPRODUCTTYPE"
}